name: mindthegap
channels:
  - conda-forge
dependencies:
  - python=3.11
  - joblib
  - jupyter
  - lightgbm>=4.6
  - matplotlib
  - numpy<2
  - pandas
  - rdkit=2023.09.1
  - scikit-learn
  - pip
  - pip:
      - torch
      - torch-geometric
