name: mindthegap

channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - joblib
  - jupyterlab
  - lightgbm
  - matplotlib
  - numpy<2
  - pandas
  - rdkit
  - scikit-learn
  - pip:
      - torch
      - torch-geometric